force-app/main/default/objects/Jedi__c/Jedi__c.object-meta.xml
<CustomObject>
    <label>Jedi</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jedi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Jedi__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The elimination of a Jedi can only be assigned to Lord Vader or a bounty hunter.</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>LordVader, BountyHunter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Jedi</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Jedi__c/fields/Lightsaber_Color__c.field-meta.xml
<CustomField>
    <fullName>Lightsaber_Color__c</fullName>
    <label>Lightsaber Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Jedi__c/fields/Number_of_Hands__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hands__c</fullName>
    <label>Number of Hands</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Jedi__c/fields/Planet__c.field-meta.xml
<CustomField>
    <fullName>Planet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Planet</label>
    <referenceTo>Planet__c</referenceTo>
    <relationshipLabel>Jedi</relationshipLabel>
    <relationshipName>Jedi</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Jedi__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Human</fullName>
            </value>
            <value>
                <fullName>Twi&apos;lek</fullName>
            </value>
            <value>
                <fullName>Zabrak</fullName>
            </value>
            <value>
                <fullName>Togruta</fullName>
            </value>
            <value>
                <fullName>Cerean</fullName>
            </value>
            <value>
                <fullName>Nautolan</fullName>
            </value>
            <value>
                <fullName>Miralan</fullName>
            </value>
            <value>
                <fullName>Kel Dor</fullName>
            </value>
            <value>
                <fullName>Iktotchi</fullName>
            </value>
            <value>
                <fullName>Tholothian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Jedi__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Padawan</fullName>
            </value>
            <value>
                <fullName>Jedi Knight</fullName>
            </value>
            <value>
                <fullName>Jedi Master</fullName>
            </value>
            <value>
                <fullName>Youngling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Planet__c/Planet__c.object-meta.xml
<CustomObject>
    <label>Planet</label>
    <nameField>
        <label>Planet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/empireForeverController.cls
public class empireForeverController {
	@AuraEnabled
    public static List<Jedi__c> getJedi(){
        List<Jedi__c> jediList = [SELECT Id, Name, Planet__r.Name, Lightsaber_Color__c, Race__c, Number_of_Hands__c, 
                                  Eliminated__c, Rank__c FROM Jedi__c]; 
        return jediList;
    }
    
    @AuraEnabled
    public static List<String> getPlanets(){
        List<String> planetNames = new List<String>();
        List<Planet__c> planets = [SELECT Id, Name FROM Planet__c];
        for(Planet__c p : planets){
            planetNames.add(p.Name);
        }
        return planetNames;
    }
    
    @AuraEnabled
    public static List<String> getRanks(){
        List<Schema.PicklistEntry> rankPicklist = Jedi__c.Rank__c.getDescribe().getPicklistValues();
        List<String> ranks = new List<String>();
        for(Schema.PicklistEntry pe: rankPicklist){
            ranks.add(pe.getValue());
        }
        return ranks;
    }
    
    @AuraEnabled
    public static List<User> getUsers(){
        return [SELECT Id, Name FROM User WHERE Profile.Name='LordVader' OR Profile.Name='BountyHunter'];
    }
    
    @AuraEnabled
    public static void setAssignment(String jediId, String chosenUser){
        Jedi__c jedi = [SELECT Id, Assigned_To__c FROM Jedi__c WHERE Id=:jediId];
        User eliminator = [SELECT Id FROM User WHERE Name=:chosenUser];
        jedi.Assigned_To__c = eliminator.Id;
        update jedi;
    }
}